#!/bin/sh
# Koonix 2020-08-27


# Config
repopath="${HOME}/.dotfiles"
histfile="${HOME}/cron-dotfiles-history.txt"

# Format date and time to make it beautiful
date_and_time="$(/usr/bin/date -Is | awk 'BEGIN{FS=OFS="+"} {gsub(/T/, " xx ", $1); print $1}')"

# Write date and time to history.txt
echo "$date_and_time" > "$histfile" || exit 1

# Stage all untracked files
git -C "$repopath" add -A 2>&1 || exit 1

# Commit all the changes and append output to history.txt
git -C "$repopath" commit -am "fcron commit at ${date_and_time}" >> "$histfile" 2>&1 || exit 1

# Add newline in history.txt
echo >> "$histfile" || exit 1

# Push
git -C "$repopath" push >> "$histfile" 2>&1 || exit 1
