#!/bin/sh
# Koonix 2020-08-27


# Config
repopath="${HOME}/.local/bin"
histfile="${HOME}/cron-scripts-history.txt"

# Format date and time to make it beautiful
date_and_time="$(/usr/bin/date -Is | awk 'BEGIN{FS=OFS="+"} {gsub(/T/, " xx ", $1); print " " $1}')"

echo "$repopath"
echo "$date_and_time"
# Commit and push all changes to ~/.local/bin scripts.
cd "$repopath" || echo "ERROR: Cannot change directory to $repopath"; exit 1

# Write date and time to history.txt
echo "$date_and_time" > "$histfile" || echo "ERROR echo"

## Commit all the changes and append output to history.txt
#git commit -am "fcron commit at ${date_and_time}" >> "$histfile" 2>&1 || echo "ERROR commit"
#
## Add newline in history.txt
#echo >> "$histfile" || echo "ERROR newline"
#
## Push
#git push >> "$histfile" 2>&1 || echo "ERROR push"
