#!/bin/sh
# convert file extentions from upper to lower case recursively.

echo "This program will now convert file extentions from upper to lower case recursively."
printf "press enter to continue..."
read x

find . -name '*.*' -exec sh -c '
  a=$(echo "$0" | sed -r "s/([^.]*)\$/\L\1/");
  [ "$a" != "$0" ] && mv "$0" "$a" ' {} \;

echo "done."
