#!/bin/sh
# automatic session locking on idle

# Config
lock_delay_minute=10

pid="$(pgrep autolock | wc -l )"
[ "$pid" -gt 2 ] && echo "autolock is already running" && exit
lock_delay_msec=$(( lock_delay_minute * 60 * 1000 ))
while true; do
    idle="$(xprintidle)"
    [ "$idle" -ge "$lock_delay_msec" ] &&
        mpv-control isallpaused &&
        sysact lock --invoked-by-autolock
    sleep 15
done
