#!/bin/sh
# Build some lists of my installed packages and put them somewhere.
#
# This script is run as root from a pacman hook, so at the end I have to
# chown the generated lists to myself.

user="koonix"
group="wheel"
path="/home/${user}/.config/bacpac"
file_offirepo="${path}/official-repo.list"
file_aur="${path}/aur.list"
file_all="${path}/all.list"

rm -f "$file_offirepo" "$file_aur" "$file_all"

/usr/bin/pacman -Qqne \
    > "$file_offirepo"

/usr/bin/pacman -Qqme \
    > "$file_aur"

/usr/bin/pacman -Qq   \
    > "$file_all"

chown -R ${user}:${group} "$path"/*
