#!/bin/sh
# Launch hydroxide server for connecting to protonmail, then launch claws-mail.
# And close the server after claws-mail is closed.

server=true
case "$1" in
    -ns) server=false; shift ;;
esac

if [ "$server" = "true" ]; then
    hydroxide serve &
fi

[ -n "$1" ] && git checkout "$1"

claws-mail --alternate-config-dir "${XDG_DATA_HOME}/claws-mail"

[ "$server" = "true" ] && killall hydroxide && echo hydroxide killed
