#!/bin/sh
# Turn off the monitor.

xset dpms force off
sleep 0.2 && xset dpms force off
sleep 0.2 && xset dpms force off
sleep 0.2 && xset dpms force off
sleep 0.2 && xset dpms force off
sleep 0.2 && xset dpms force off
