#!/bin/sh

src="/mnt/drives/d/downloads/artix/firefox/cookies.txt"

[ ! -r "$src" ] &&\
    src="/mnt/drives/d/downloads/artix/firefox/cookie/cookies.txt"

[ ! -r "$src" ] &&\
    echo "cookie file not found" && exit 1

dest="${HOME}/.local/share/ytdl-cookies/youtube.cookie"

mv -fv "$src" "$dest" || echo "mv error"

chmod -v a-x "$dest" || echo "chmod error"

exit 0
