#!/bin/sh
# This script does the following:
#	Run by itself, set the wallpaper (at X start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.

# Make the directory
mkdir -p "$XDG_DATA_HOME/paper"

# Path to symlink to wallpaper
wall_main="$XDG_DATA_HOME/paper/wall_main"

# Path to a backup wallpaper to use if the actual one is cucked
wall_bak="$XDG_DATA_HOME/paper/wall_bak"

# Set wallpaper using feh.
apply_wall() {
    feh --no-fehbg --bg-fill "$wall_main" ||
    feh --no-fehbg --bg-fill "$wall_bak"
}

wall_link="$wall_main"

######################################
# Handle -b option
case "$1" in

    -b | --backup)

        bak=true
        wall_link="$wall_bak"
        bak_word="Backup "
        shift
        ;;

    -h | --help)

        echo "wallpaper handler"
        exit 0
        ;;
esac
######################################

selected_wall="$(readlink -f "$1")"

######################################
# Handle given wallpapers or directories

if [ -f "$1" ]; then

    ln -sf "$selected_wall" "$wall_link" &&
    notify-send -i "$wall_link" "Changing ${bak_word}Wallpaper..."

    [ "$bak" = true ] &&
    rm "$wall_link" &&
    cp -f "$selected_wall" "$wall_link"

elif [ -d "$1" ]; then

    selected_path="$selected_wall"

    selected_random_wall="$(\
    find "$selected_path" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f |
    shuf -n 1)"

    ln -sf "$selected_random_wall" "$wall_link" &&
    notify-send -i "$wall_link" "Random ${bak_word}Wallpaper Chosen."

    [ "$bak" = true ] &&
    rm "$wall_link" &&
    cp -f "$selected_random_wall" "$wall_link"

fi
######################################

# Apply wallpepr
apply_wall
