#!/bin/sh
# this script connects to my router via telnet and reboots it.

sv=192.168.1.1
user=admin
pass=ur@b1g5uy4U

cmdlist="
$user
$pass
reboot
"

(
    sleep 0.2
    printf "$cmdlist" | awk NF | while IFS= read -r cmd; do
        sleep 0.1
        printf "${cmd}\r"
    done
    sleep 0.2
) | telnet $sv
