#!/bin/sh
# Hide a firefox window to keep it running in the background
# for faster firefox startup.

# Config
file="/tmp/stalonetray-hide"

hide_current()
{
    xdotool search --name "stalonetray" |
    awk '{print $0; exit}' |
    tee "$file" |
    xargs xdotool windowunmap
}

show_hidden()
{
    [ ! -r "$file" ] && return
    xdotool windowmap "$(cat "$file")"
}

case "$1" in
  init) stalonetray --config $STALONETRAYRC &
        sleep 2; stalonetray-hide on ;;
  on)   show_hidden; hide_current ;;
  on-delayed) sleep 1; show_hidden; hide_current ;;
  off)  show_hidden; rm -f "$file" ;;
  *)    echo "give arg"; exit 1 ;;
esac
