#!/bin/sh
# Get a path and open a terminal in that path.

cd "$1"
setsid -f $TERMINAL -e /bin/sh -c '$RANGER; exec $SHELL' > /dev/null 2>&1
sleep 0.3
setsid -f opaque -r $TERMINAL >/dev/null 2>&1
exit 0
