#!/bin/sh
# Restart the tor service, and notify when it reconnects successfully.

# Config
user="koonix"

# Restart the service
if [ "$1" != "--quiet" ]; then :;
    # sudo -u "$user" notify-send "Restarting Tor..."
fi
sv restart tor

# Refresh my bar
sudo -u "$user" dwmbarref tor

# Log a message that tor was restarted.
sudo -u "$user" logger -t tor-reset "tor restarted" &

# Wait for it to connect to tor network, and notify when it does.
( tail -n 0 -F "/var/log/everything.log" & ) |
    grep -q "Bootstrapped 100"

if [ "$1" != "--quiet" ]; then
    sudo -u "$user" notify-send "Tor Restarted Successfully"
fi
