#!/bin/sh
# Check if uget/aria2 has any active downloads every x seconds.
# if no active downloads detected for n cycles,
# suspend the system (with n minutes of delay).

# Config
interval_seconds=20
ncycles=3

# delay after all downloads complete and before suspending the system
delay_minutes=1

# Exit if uget not running.
text="$(aria2p show 2>&1 | awk '{print $3; exit}')"
[ "$text" != "PROGRESS" ] && echo "error: cannot connect to uget/aria2." && exit 1

echo "connected to uget."
echo "go to sleep now. we're good."

get_active_dl_count()
{
    aria2p show | awk '$2~/active/' | wc -l
}

i=0;
while true; do

    sleep "$interval_seconds"

    if [ "$(get_active_dl_count)" = "0" ]; then
        i=$(( i + 1 ))
        notify-send "uget-sysact" \
            "uget downloads complete. suspending in a few seconds."
    else
        i=0
    fi

    if [ "$i" -ge "$ncycles" ]; then
        echo "all uget downloads complete."
        echo "suspending in $delay_minutes minutes."
        sleep ${delay_minutes}m
        echo; echo
        clock
        echo "all uget downloads complete."
        echo "suspending now."
        echo; echo
        logger -t uget-sysact "uget downloads complete, suspending system now."
        sysact suspend
        logger -t uget-sysact "system awaken."
        exit
    fi
done
