#!/bin/sh

file="$XDG_CONFIG_HOME/uGet/Setting.json"
line='			"name": 300,'

new_file="$(
    awk '/\s"Width":\s/ {print NR; exit}' "$file" |
        xargs -I {} awk -v line="$line" '
            {if(NR == {}+2) print line; else print $0}' "$file"
    )"

echo "$new_file" > "$file"
