#!/bin/sh
# switch to tag 5 if ffgather is running; open firefox if not.

set -E
trap '[ "$?" -ne 77 ] || exit 77' ERR

pgrep -f 'gather firefox' &&
    (xdotool search --class firefox | grep -q $(xdotool getactivewindow) ||
    (dwmc view 5; exit 77))

find /run/user/1000 -name 'firefox*' | wc -l | grep -v -q '0' &&
    setsid -f $BROWSER && vrs || notify-send firefoxwtf
