#!/bin/sh

# Kill any leftovers from previous runs
kill_stuff() {
    killall youtube-dl >/dev/null 2>&1
    killall mpv >/dev/null 2>&1
}

# If got the kill command, just kill the stream and exit
if [ "$1" = "k" ] || [ "$1" = "kill" ]
then
    kill_stuff
    exit 0
fi

# Play lofi hip hop lmao
kill_stuff
2>/dev/null youtube-dl -f 95 -q -o - \
    "https://www.youtube.com/watch?v=5qap5aO4i9A" | mpv - >/dev/null 2>&1 &
