#!/bin/sh
# Koonix 2020-08-19 ﴘ

# A dmenu wrapper script for system functions.

cmds="\
 lock		lock
⏻ kill xorg	dmenu-killxorg
⏻ shutdown	dmenu-shutdown
 reboot	dmenu-reboot"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1
`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
