#!/bin/bash
# A bashmount-style ftp mounting script.
# It Mounts my phone's ftp server (powered by solid explorer).
# You can use it to mount any ftp server though.
#
# The ftp server's user and pass is in ~/.netrc (which is read by ftp itself),
# So I don't have to type it in everytime.
#
# Here is my .netrc contents:
#
# machine 192.168.1.15
# login koonix
# password mypassword


# Config
ftp_ip="192.168.1.15:9999"
mnt_path="$HOME/Mount/FTP"

main()
{
    # Big boy ethernal while loop
    while true; do

    clear
    helper_text
    read -p "Command: " entered_command

    case "$entered_command" in
        m) ftp_mount; continue ;;
        u) ftp_unmount; continue ;;
        f) ftp_force_unmount; continue ;;
        o) open; continue ;;
        q) exit 0 ;;
        "") continue ;;
        *) command_output="Invalid Command" ;;
    esac
    done
}

ftp_mount()
{
    command_output="$(
        (grep -q "$ftp_ip" /etc/mtab && echo "Already Mounted") ||
        (2>&1 curlftpfs -o utf8 "ftp://${ftp_ip}" "$mnt_path" &&
        echo "FTP Mounted")
        )"
}

ftp_unmount()
{
    command_output="$(
        fusermount -u "$mnt_path" 2>&1 && echo "FTP Unmounted"
        )"
}

ftp_force_unmount()
{
    command_output="$(
        2>&1 sudo umount "$mnt_path" && echo "FTP Unmounted"
        )"
}

open()
{
    termopen "$mnt_path"
}

helper_text()
{
echo -e "${command_output}

━━━━━━━━━━━ Commands ━━━━━━━━━━━━

  m: mount        o: open

  u: unmount      f: force unmount

  enter: redraw   q: quit

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"
}

# Run the main function
main; exit
