#!/bin/bash
# Koonix 2020-08-19

# Send SIGTRAP signal to sucklessbar script, which will run a specified function
# upon receiving this signal.

bar_refresh() {
    killall -s SIGTRAP sucklessbar > /dev/null 2>&1
}

case "$1" in
    -r)
        count="$2"
        interval="$3"
        for (( i=0; i<count; i++ )); do
            bar_refresh
            sleep "$interval"
        done &
        ;;
    -h | --help)
        echo -e "usage:\e
        refresh the bar once:
            sucklessbar-refresh

        refresh the bar a number of times at fixed intervals:
            sucklessbar-refresh [-r] <number of refreshes> <interval>"
        ;;
    *)
        bar_refresh
        ;;
esac
exit 0
