#!/bin/bash
# Koonix 2020-08-23
# This script be responsible for me statusbar.

##############################################################################
# Configuration
##############################################################################
#
# Bar update interval
interval=6
#
# The delimiter character(s) between widgets
# The escape sequences \x01 through \x06 represent colors
delimiter="\x05 ][ \x06"
#
# The half-delimiter at the end of the bar
enddelimiter="\x05 ]"
#
# Whatever you want to show up at the beginning of the bar
bar_prefix=" "
#
# Glyphs/Emojis
glyph_headphone=""
glyph_keyboard=""
glyph_speaker=""
glyph_memory=""
glyph_geoip=""
glyph_geoip_tor=""
glyph_temp=""
glyph_time=""
#
# Position of widgets
widpos_time="\
    1"
widpos_kblayout="\
    2"
widpos_audio="\
    3"
widpos_geoip="\
    4"
widpos_cpu="\
    5"
widpos_mem="\
    6"
#
##############################################################################
# End of Configuration
##############################################################################

# Main function
main() {
    if [[ $1 = -h ]] ||
       [[ $1 = --help ]]; then
       echo "statusbar script for suckless's dwm"
       exit 0
    fi
    # Refresh the statusbar every 2 seconds
    while true ; do
        refresh_bar
        sleep "$interval" &
        wait
    done
}

#############
# FUNCTIONS #
#############

######
# Construct the statusbar
refresh_widgets_set1() {

    # Time and date widget
    WIDGET[$widpos_time]=$(widget_time)

    # Volume widget
    refresh_widgets_set2

    # GeoIP widget
    WIDGET[$widpos_geoip]=$(widget_geoip)

    # CPU temp widget
    WIDGET[$widpos_cpu]=$(widget_cpu)

    # Memory usage widget
    WIDGET[$widpos_mem]=$(widget_mem)
}

# Construct the statusbar while updating only some of the widgets
refresh_widgets_set2() {

    # Keyboard layout widget
    WIDGET[$widpos_kblayout]=$(widget_kb_layout)

    # Audio widget
    WIDGET[$widpos_audio]=$(widget_audio)

    # Geoip widget
    WIDGET[$widpos_geoip]="$geoip_last_output"
}
######



######
# Widget that shows time and date.
widget_time() {

    echo "$(date -Im | \
        awk -v glyph="$glyph_time" 'BEGIN{FS=OFS="+"} \
        {gsub(/T/, " x ", $1); print glyph " " $1}')"
}

# Widget that shows the current keyboard layout.
widget_kb_layout() {

    echo "$glyph_keyboard"; echo "$(xkblayout-state print " %s")"; echo
}

# Widget that shows some audio related stuff.
widget_audio() {

    # Check if audio is playing through headphones or speakers
    currentsink=$(vol-getcurrentsinkname)
    if [[ $currentsink = analog-stereo ]]
    then
        sinkicon="$glyph_headphone"
    else
        sinkicon="$glyph_speaker"
    fi

    echo "${sinkicon} "; echo "$(vol-getcurrentvolumeandmute)"
}

# Widget that shows memory usage.
widget_mem() {

    echo "$(free -h | \
        awk -v glyph="$glyph_memory" '/^Mem:/ {print glyph " " $3}')"
}

# Widget that shows CPU temp.
widget_cpu() {
    local cpu="$(sensors | \
        awk -v glyph="$glyph_temp" '/^Core 0/ {print glyph $3}' | tr '+' ' ')"
    echo "${cpu::-4}°C"
}

# Widget that shows your location based on your public ip.
widget_geoip() {

    local ip_direct="$(\
        curl -s --retry 1 ifconfig.me || echo "")"

    local ip_tor="$(\
        curl -x socks5://127.0.0.1:9050 -s --retry 1 ifconfig.me || echo "")"

    if [ "$ip_direct" = "" ] && [ "$ip_tor" = "" ]; then
        echo "$ip_direct"
    else
        geoip_direct="$(geoiplookup "$ip_direct")"
        geoip_tor="$(geoiplookup "$ip_tor")"

        geoip_direct="$(echo "$geoip_direct" | \
            awk \
                -v glyph="$glyph_geoip"\
                'BEGIN { FS=OFS="," }\
                /^GeoIP/ {gsub(/Iran/, "ir", $2);\
                print glyph tolower($2) " - "}')"

        [[ ! -z $glyph_geoip_tor ]] &&\
            glyph_geoip_tor="${glyph_geoip_tor} "

        geoip_tor="$(echo "$geoip_tor" | \
            awk \
                -v glyph="$glyph_geoip_tor"\
                'BEGIN { FS=OFS=", " }\
                /^GeoIP/ {print glyph tolower($2)}')"

        [ "$ip_direct" = "" ] && geoip_direct="$ip_direct"
        [ "$ip_tor" = "" ] && geoip_tor="$ip_tor"
        echo "$geoip_direct"
        echo "$geoip_tor"
    fi

}
######




######
# Now for the dirty background detail:
# Stick all the widgets together into a line
build_bar() {
    local widget_count="${#WIDGET[@]}"
    statusbar=$(for ((i = "$widget_count"; i > 0; i--))
    do
        echo "$delimiter"
        echo "${WIDGET[$i]}"
    done)
}

# Write the bar to dwm via xsetroot
write_bar() {
    # Remove the first six characters of statusbar (leftover of the delimiter)
    statusbar="${bar_prefix}${statusbar:6}${enddelimiter}"
    xsetroot -name "$(echo -e "$statusbar" | tr -d '\n')" &
    wait
}

# Refresh and write the constructed statusbar
refresh_bar() {
    refresh_widgets_set1
    build_bar
    write_bar
    # Save geoip widget's output to use it in refresh_widgets_set2
    geoip_last_output="${WIDGET[$widpos_geoip]}"
}

# Refresh and write the constructed statusbar (but only refresh set2)
refresh_bar_sigtrap() {
    refresh_widgets_set2
    build_bar
    write_bar
}
######

# Trap for updating the statusbar at will
trap 'refresh_bar_sigtrap' SIGTRAP

# Run the main function
main "$@"; exit
