#!/bin/sh
# A replacement for mv with progressbar,
#
# It's also filesystem-aware, so if you are moving files inside a filesystem,
# It falls back to mv instead of copying and then deleting, because mv is
# faster than copying and then deleting the files when moving files within
# the same filesystem/partition.

# When moving file
#rsync -a --remove-source-files --info=progress2 "$@"
#stat -c "%d" /path
#for dest; do true; done
#find "$dest" -type d -empty -delete


# fallback
mv -- "$@"
