#!/bin/sh

opaque -r $TERMINAL >/dev/null 2>&1 &

ranger_choosefiles=/tmp/nvimranger-choosefiles
nvimranger_infofile=/tmp/nvimranger

editor_file_fullpath="$(awk 'BEGIN{RS="^$";FS=OFS="\n"}{print $3; exit}' $nvimranger_infofile)"
nvim_socket="$(         awk 'BEGIN{RS="^$";FS=OFS="\n"}{print $2; exit}' $nvimranger_infofile)"

while true; do
    rm -f $ranger_choosefiles
    $RANGER --selectfile="$editor_file_fullpath" --choosefiles=$ranger_choosefiles
    [ ! -r "$ranger_choosefiles" ] && exit 1
    cat $ranger_choosefiles | xargs nvr --servername $nvim_socket --remote
    editor_file_fullpath="$(cat $ranger_choosefiles | tail -n1)"
done
