#!/bin/sh
# Koonix 2020-08-30

# Get rid of those ugly borders in vim by setting the background color of
# the terminal to the same color as vim's (using an ANSI escape sequence),
# and restoring it to however it was after exiting vim.

# Config
default_bg="#1a1d24"
nvim_bg="#262626"

# Set terminal's background to the given hex color.
term_bg() { \
    local color="$1"
    echo -ne "\\033]11;${color}\\007"
}

# Set colors, launch nvim, revert colors after nvim is done.
term_bg "$nvim_bg"
/usr/bin/nvim "$@"
term_bg "$default_bg"
