#!/bin/sh
#                 M A N - P A G E S    I N    V I M

if [ "$#" -eq "0" ]; then
  echo "What manual do you want bruv?";
  exit 0
elif ! man -w "$@" > /dev/null; then
  # Check if that manpage exists to prevent visual noise or whatever.
  exit 1
fi

"$EDITOR" -c "SuperMan $*" -c "set number"
