#!/bin/bash
# A bashmount-style ftp mounting script.
# It Mounts my phone's ftp server (powered by solid explorer).
# You can use it to mount any ftp server though.
#
# The ftp server's user and pass is in ~/.netrc (which is read by ftp itself),
# So I don't have to type it in everytime.
#
# Here is my .netrc contents:
#
# machine 192.168.1.15
# login koonix
# password mypassword


# Config
ftp_ip="192.168.1.15:9999"

main() {
    # Big boy ethernal while loop
    while true; do

    clear
    helper_text
    read -p "Command: " entered_command

    case "$entered_command" in
        m) ftp_mount; continue ;;
        u) ftp_unmount; continue ;;
        q) exit 0 ;;
        *) command_output="Command invalid" ;;
    esac
    done
}

ftp_mount() {
    command_output="$(
        2>&1 curlftpfs -o utf8 "ftp://${ftp_ip}" ~/Mount/FTP &&
        echo "FTP Mounted")"
}

suprompt="
UnMounting as user failed, trying as root now
[sudo] password for %p: "

ftp_unmount() {
    command_output="$(
        fusermount -u ~/Mount/FTP 2>&1 && echo "FTP UnMounted" ||
        echo "UnMounting as user failed, trying as root now" &&
        sudo -p "$suprompt" umount ~/Mount/MTP 2>&1 && echo "FTP UnMounted"
        )"
}

helper_text() {
echo -e "${command_output}

━━━━━━━━━━━━ Commands ━━━━━━━━━━━

m: mount    u: unmount    q: quit

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"
}

# Run the main function
main; exit
