#!/bin/sh
# This script toggles the default audio
# sink AND the audio sink of active streams
# between two (or more) sink devices.

# Set temp file paths
currentsinkfile="$(find -P /tmp -maxdepth 1 -name volctl\*)"
[ -z "$currentsinkfile" ] &&\
    { echo "error: volctl temp file not found" ; exit 1; }

currentsink=$(cat "$currentsinkfile")

# Check the current sink device from the temp file and toggle it's value
if [ "${currentsink}" = "analog-stereo" ]
then
# Get the index of sink device
    speakers="$(pactl list short sinks | awk '/hdmi-stereo/ {print $1}')"
    newsinkdevice="$speakers"
    echo "hdmi-stereo" > "$currentsinkfile"
else
# Get the index of sink device
    headphones="$(pactl list short sinks | awk '/analog-stereo/ {print $1}')"
    newsinkdevice="$headphones"
    echo "analog-stereo" > "$currentsinkfile"
fi

# Select the new device as default
pactl set-default-sink "$newsinkdevice"

# Change default device of all running audio streams
pactl list short sink-inputs | while read -r stream; do
    streamid=$(echo "$stream" | awk '{print $1}')
    pactl move-sink-input "$streamid" "$newsinkdevice"
done
