#!/bin/sh
# Same as vol-getcurrentvolume, but puts $MUTE_INDICATOR next to the volume
# percentage, if the current audio output device is muted.

MUTE_INDICATOR=""

CURRENTSINK=$(vol-getcurrentsinkname)

VOLUME=$( pactl list sinks | grep -v snd_aloop | awk -v pattern="$CURRENTSINK" '$2~pattern {nr[NR+7]}; NR in nr {print $5}')
ISMUTED=$(pactl list sinks | grep -v snd_aloop | awk -v pattern="$CURRENTSINK" '$2~pattern {nr[NR+6]}; NR in nr {print $2}')

if [ "$ISMUTED" = "yes" ]
then
    MUTESTATE="$MUTE_INDICATOR "
else
    MUTESTATE=
fi

echo "${MUTESTATE}${VOLUME}"
