#!/bin/sh
# Takes the current volume as an argument and rounds it up to the
# nearest multiple of $ROUND_TO. Also considers $MINVOL and $MAXVOL
# while doing so.

# Some examples (if ROUND_TO=5 and MAXVOL=100):
#
#   input value      output value
#    0                5
#    12               15
#    15               20
#    89               90
#    95               100
#    100              100

round_to=10

vol=$1
minvol=$2
maxvol=$3
if [ "$vol" -ge "$minvol" ] && [ "$vol" -lt "$maxvol" ]
then
    newvol=$((((vol+round_to)/round_to)*round_to))
    echo "$newvol"
else
    echo "$vol"
fi
