#!/bin/sh
# This script toggles the default audio
# sink AND the audio sink of active streams
# between two (or more) sink devices.

# Set temp file paths
currentsinkfile="$(find -P /tmp -maxdepth 1 -name volctl\*)"
[ -z "$currentsinkfile" ] &&
    { echo "error: volctl temp file not found" ; exit 1; }

# Check the current sink device from the temp file and re-set it's value
headphones="$(pactl list short sinks | awk '/analog-stereo/ {print $1}')"
speakers="$(pactl list short sinks | awk '/hdmi-stereo/ {print $1}')"
currentsink=$(cat "$currentsinkfile")

[ "$currentsink" = "analog-stereo" ] &&
    newsinkdevice="$headphones" ||
    newsinkdevice="$speakers"

# Select the new device as default
pactl set-default-sink "$newsinkdevice"

# Set keyboard sound effect's output to speakers
buckle=$(vol-getbuckleindex)
[ -n "$buckle" ] &&
    pactl move-sink-input "$buckle" "$speakers" ||
    buckle=notrunning

# Change default device of all running audio streams
sleep 0.1
pactl list short sink-inputs | while read -r stream; do
    streamid=$(echo "$stream" | awk '{print $1}')
    [ "$streamid" != "$buckle" ] &&
        pactl move-sink-input "$streamid" "$newsinkdevice"
done

exit 0
