#!/bin/sh
# This script toggles the default audio
# sink AND the audio sink of active streams
# between two (or more) sink devices.

# Set temp file paths
currentsinkfile="$(find -P /tmp -maxdepth 1 -name volctl\*)"
[ -z "$currentsinkfile" ] &&
    { echo "error: volctl temp file not found" ; exit 1; }

# Check the current sink device from the temp file and toggle it's value
currentsink=$(cat "$currentsinkfile")
# Get the index of sink devices
speakers="$(pactl list short sinks | grep -v snd_aloop | awk '/hdmi-stereo/ {print $1}')"
headphones="$(pactl list short sinks | grep -v snd_aloop | awk '/analog-stereo/ {print $1}')"

if [ "$currentsink" = "analog-stereo" ]; then
    newsinkdevice="$speakers"
    echo "hdmi-stereo" > "$currentsinkfile"
else
    newsinkdevice="$headphones"
    echo "analog-stereo" > "$currentsinkfile"
fi

# Select the new device as default
pactl set-default-sink "$newsinkdevice"

# Change default device of all running audio streams
pactl list short sink-inputs | while read -r stream; do
    streamid=$(echo "$stream" | awk '{print $1}')
    [ "$streamid" != "$buckle" ] &&
        pactl move-sink-input "$streamid" "$newsinkdevice"
done

exit 0
