#!/bin/sh
# Koonix 2020-08-19

# A dmenu wrapper script for system functions.

# Config
prompt_text="Select System Action:"

cmds="\
 Lock		koonix-lock
⏻ Shutdown	dmenu-shutdown
 Reboot	dmenu-reboot
⏻ Kill Xorg	dmenu-killxorg"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu -p "$prompt_text")" || exit 1
`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
