#!/bin/sh
# Koonix 2020-08-19 ﴘ

# A dmenu wrapper script for system functions.

cmds="\
 Lock		lock
⏻ Kill Xorg	dmenu-killxorg
⏻ Shutdown	dmenu-shutdown
 Reboot	dmenu-reboot"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1
`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
