#!/bin/sh

main() {
case "$1" in
    -F)
         [ -z "$2" ] && exit 0
         qual "$2" ;;
     *)
         if   [ -z "$1" ]; then exit 0
         elif [ -z "$2" ]; then dl "$1"
         else dlqual "$@"
         fi ;;
esac
}

qual() {
youtube-dl -4 --proxy 127.0.0.1:8123 \
        --cookies "${HOME}/.local/share/ytdl-cookies/youtube.cookie" \
        -F "$1" && exit 0
}

dlqual() {
[ ! -z "$2" ] && \
youtube-dl -4 --proxy 127.0.0.1:8123 \
        --cookies "${HOME}/.local/share/ytdl-cookies/youtube.cookie" \
        -f "$2" "$1" && exit 0
}

dl() {
[ ! -z "$1" ] && \
youtube-dl -4 --proxy 127.0.0.1:8123 \
        --cookies "${HOME}/.local/share/ytdl-cookies/youtube.cookie" \
        "$1" && exit 0
}

main "$@"; exit 0
