#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform commands $2 to infinity.
# For example:
# `./prompt "Do you want to shutdown?" shutdown -h now`

[ "$(printf "No\\nYes" |
    dmenu -p "$1" -nb darkred -sb red -sf white -nf gray )" = "Yes" ] || exit 1
shift
[ -n "$*" ] && /bin/sh -c "$@"
exit 0
