#!/bin/sh
# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
CHOSEN=$(cut -d ';' -f1 ~/.config/emoji/emoji.list | dmenu -fn "peep:size=15"  -l 30 | sed "s/ .*//")

# Exit if none CHOSEN.
[ -z "$CHOSEN" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	xdotool type "$CHOSEN"
else
	echo "$CHOSEN" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$CHOSEN' copied to clipboard." &
fi
