#!/bin/sh

# Config
prompt_text="Reboot to:"

cmds="\
 Default	:
 Windows	sudo -A grub-reboot Windows"

choice="$(echo "$cmds" | cut -d'	' -f 1 |
    dmenu -p "$prompt_text")" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`

dmenu-prompt "Really Reboot?" sudo -A reboot
