#!/bin/sh

# =========
# = Config
# =========

prefix="[ "
suffix=" ]"
prompt="Choose printer:"

delimiter="->"

actions="
HP Laser Printer-> prnt HP_M1132
Epson Photo Printer-> prnt EPSON_L800
"


# ============================
#  ======= Functions ========
# ============================

# Handle options and stuff
main()
{
    case "$1" in
        -epson | -photo | -ink) eps "$@" ;;
        -hp | -laser | -toner) hp "$@" ;;
        *) ask "$@" ;;
    esac
}

ask()
{
    [ -z "$*" ] && echo give file to print && exit 1
    # Selec an action via dmenu
    selected_action="$(
        echo "$actions" | awk NF |
            awk -F "$delimiter" -v pf="$prefix" -v sf="$suffix" '
            {print pf $1 sf}' | dmenu -p "$prompt"
    )"

    # Exit if nothing selected in dmenu
    [ -z "$selected_action" ] && exit 1

    # remove prefix and suffix
    selected_action=${selected_action#"$prefix"}
    selected_action=${selected_action%"$suffix"}

    # Extract the command of that action
    action_cmd="$(
        echo "$actions" | awk NF |
            awk -F "$delimiter" -v ptrn="$selected_action" '
            $1==ptrn {for (i=2; i<=NF; i++) print $i; exit}'
    )"

    eval "$action_cmd" "$@"
}

prnt()
{
    msg="$(2>&1 /usr/bin/lp -q 20 -d "$@")"
    /usr/bin/notify-send -u low -- "Printing via $1" "$msg"
}

main "$@"
exit
