#!/bin/sh
# Show some options to launch some mounting scripts with dmenu.

# =========
# = Config
# =========
terminal=st
terminal_alt=st-alt
#
prompt="Mount What?"
prefix=""
suffix=""
delimiter="-> "
#
actions="
 USB-> mount_usb
 MTP-> mount_mtp
ﴓ FTP-> mount_ftp
"

main()
{
case "$1" in
    usb) mount_usb ;;
    mtp) mount_mtp ;;
    ftp) mount_ftp ;;
    *) ask ;;
esac
}

ask()
{
    # Selec an action via dmenu
    selected_action="$(
        echo "$actions" | awk NF |
            awk -F "$delimiter" -v pf="$prefix" -v sf="$suffix" '
            {print pf $1 sf}' | dmenu -p "$prompt"
    )"

    # Exit if nothing selected in dmenu
    [ -z "$selected_action" ] && exit 1
    # remove prefix and suffix

    selected_action=${selected_action#"$prefix"}
    selected_action=${selected_action%"$suffix"}

    # Extract the command of that action
    action_cmd="$(
        echo "$actions" | awk NF |
            awk -F "$delimiter" -v ptrn="$selected_action" '
            $1==ptrn {for (i=2; i<=NF; i++) print $i; exit}'
    )"

    eval "$action_cmd"
}


mount_usb()
{
    $terminal_alt -e bashmount &
    sleep 0.3
    opaque -r $terminal
}

mount_mtp()
{
    $terminal_alt -e bashmtp &
    sleep 0.3
    opaque -r $terminal
}

mount_ftp()
{
    $terminal_alt -e bashftp &
    sleep 0.3
    opaque -r $terminal
}

main "$@"
exit
