#!/bin/sh
# An improved version of Luke Smith's shitty screenshot script.
#
# give it the -c or --copy flag to copy to clipboard instead of saving to file.
#
# Screenshot script, requires maim, and my clock script. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

# Config
delay="0.2"
prompt="Screenshot Method:"
prompt_copy="Screenshot method (copy to clipboard):"
save_to="/mnt/drives/d/downloads/artix/screenshot"

# prefix and suffix should be
prefix=""
suffix=""

# define action names and their commands
delimiter="->"
actions="
FullScreen-> full
Select Area-> sele
Current Window-> wndw
"

# Functions
main()
{
    copy_to_clipboard=false
    while true; do
        case "$1" in
            -c|--copy) shift; copy_to_clipboard=true ;;
            f|full|fullscreen)   full; break 2 ;;
            s|sele|select)       sele; break 2 ;;
            w|wndw|window)       wndw; break 2 ;;
                       "") ask; break 2 ;;
                        *) echo "bad arg"; exit 1 ;;
        esac
    done
}

ask()
{
    # Selec an action via dmenu,
    # and add prefix and suffix to the action's name
    pr="$prompt"
    [ "$copy_to_clipboard" = "true" ] && pr="$prompt_copy"
    selected_action="$(
        echo "$actions" | awk NF |
            awk -F "$delimiter" -v pf="$prefix" -v sf="$suffix" '
            {print pf $1 sf}' | dmenu -p "$pr"
    )"

    # Exit if nothing selected in dmenu
    [ -z "$selected_action" ] && exit 1

    # remove prefix and suffix
    selected_action=${selected_action#"$prefix"}
    selected_action=${selected_action%"$suffix"}

    # Extract the command of that action
    action_cmd="$(
        echo "$actions" | awk NF |
            awk -F "$delimiter" -v ptrn="$selected_action" '
            $1==ptrn {for (i=2; i<=NF; i++) print $i; exit}'
    )"

    eval "$action_cmd"
}


full()
{
    sleep "$delay"
    [ "$copy_to_clipboard" = "true" ] && full_cp && return
    maim -u ${save_to}/sc-full_"$(clock -f).png"
}
full_cp()
{
    maim -u | xclip -selection clipboard -t image/png
}


sele()
{
    sleep "$delay"
    [ "$copy_to_clipboard" = "true" ] && sele_cp && return
    maim -u -s ${save_to}/sc-sele_"$(clock -f).png"
}
sele_cp()
{
    maim -u -s | xclip -selection clipboard -t image/png
}


wndw()
{
    sleep "$delay"
    window="$(xdotool getactivewindow)"
    [ "$copy_to_clipboard" = "true" ] && wndw_cp && return
    maim -u -i "$window" ${save_to}/sc-wndw_"$(clock -f).png"
}
wndw_cp()
{
    maim -u -i "$window" | xclip -selection clipboard -t image/png
}

main "$@"
exit
