#!/bin/sh

# common
export volatile_dir=/mnt/zramfs/sync

# firefox
export name=ccls
export target_dir=$HOME/.cache/ccls-cache-log/ccls
export perm=0755

memsync

# ccls-neovim
export name=firefox
export target_dir=$HOME/.mozilla/firefox/wn1iogv8.default-release
export perm=0700

memsync
