#!/bin/sh

# Get the index of sink devices
speakers="$(pactl list short sinks | grep -v snd_aloop | awk '/hdmi-stereo/ {print $1}')"
headphones="$(pactl list short sinks | grep -v snd_aloop | awk '/analog-stereo/ {print $1}')"

# Get arg
[ -z "$1" ] && exit 1
eval "sink=\"\$$1\""
[ -z "$sink" ] && exit 1

# Set keyboard sound effect's output to speakers
buckle=$(vol-getbuckleindex)
[ -n "$buckle" ] &&
    pactl move-sink-input "$buckle" "$sink" ||
    buckle=notrunning

exit 0
