#!/bin/sh

# Set layout and model, also map capslock to super
setxkbmap -model pc105 -layout us,ir -option "caps:super"

# But treat capslock as escape if pressed and released
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'

# Set key repeat rate
 xset r rate 300 50

# Turn off key repeat for media keys
xset -r 121
xset -r 122
xset -r 123

# Disable mouse acceleration
xset m 0 0
