#!/bin/sh

# Set keyboard layout and model
setxkbmap -model pc105 -layout us,ir

# Remap one of my mouse's side buttons to middle click
xmodmap -e "pointer = 1 9 3 4 5 6 7 8 2 10"

# Left super acts as escape if pressed and released
# (Capslock is mapped to left super via skr)
killall xcape 2>/dev/null
xcape -e 'Super_L=Escape'

# Advanced: Left ctrl acts as space if pressed and released
# (Space is mapped to left ctrl via skr)
# xcape -e 'Super_L=Escape;Control_L=space'

# Advanced: Set key repeat rate
xset r rate 300 50

# Turn off key repeat for media keys
xset -r 121
xset -r 122
xset -r 123

# Disable mouse acceleration
xinput --set-prop 'pointer:G-SPY USB Gaming Mouse' 'libinput Accel Profile Enabled' 0, 1
