#!/bin/sh
# You can control dwm with this script.

# Config
layout_list="
decktile
deck
grid
nrowgrid
tile
dwindle
spiral
cmaster
cfmaster
monocle
float
"

main ()
{
case "$1" in

  layout)
    shift;
    case "$1" in
      decktile) set_layout 1;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL && dwmc resmfact ;;
      deck)     set_layout 2;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL && dwmc resmfact ;;
      grid)     set_layout 3;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL ;;
      nrowgrid) set_layout 4;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL ;;
      tile)     set_layout 5;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL && dwmc resmfact ;;
      dwindle)  set_layout 6;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL && dwmc resmfact ;;
      spiral)   set_layout 7;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL && dwmc resmfact ;;
      cmaster)  set_layout 8;  [ "$2" != "--no-extra" ] && opaque -0 $TERMINAL && dwmc resmfact ;;
      cfmaster) set_layout 9;  [ "$2" != "--no-extra" ] && opaque -2 $TERMINAL && dwmc setmfact 1.9 ;;
      monocle)  set_layout 10;  [ "$2" != "--no-extra" ] && opaque -1 $TERMINAL ;;
      float)    set_layout 11; [ "$2" != "--no-extra" ] && opaque -1 $TERMINAL ;;
      *) exit 1 ;;
    esac
    exit
  ;;

  view|toggleview|tag|toggletag) dwm-msg run_command "$1" $(getbin "$2") ;;
  toggleviewmaster | switchcol) dwm-msg run_command switchcol ;;
  addviewright) dwmc toggleview "$(echo "$(get_current_tag)+1" | bc)" ;;
  viewall) dwm-msg run_command view 511 ;;
  tagall) dwm-msg run_command tag 511 ;;

  next) dwm-msg run_command focusstack  1 ;;
  prev) dwm-msg run_command focusstack -1 ;;

  supernext) [ "$(get_current_layout_name)" = "deck" ] &&
      dwm-msg run_command inplacerotate '-1' || dwm-msg run_command focusstack 1 ;;
  superprev) [ "$(get_current_layout_name)" = "deck" ] &&
      dwm-msg run_command inplacerotate 1 || dwm-msg run_command focusstack '-1' ;;

  incmfact) dwm-msg run_command setmfact   0.025  ;;
  decmfact) dwm-msg run_command setmfact '-0.025' ;;
  resmfact) dwm-msg run_command setmfact 1.5 ;;

  getnmaster) get_numberof_masters ;;
  incnmaster) dwm-msg run_command incnmaster   1  ;;
  decnmaster) dwm-msg run_command incnmaster '-1' ;;
  resnmaster)
      case $(get_numberof_masters) in
          0) dwmc incnmaster ;;
          *) while [ "$(get_numberof_masters)" -gt 1 ]
                 do dwmc decnmaster; done ;;
      esac ;;

  setnmaster | setrow)
      dwmc resnmaster
      dwm-msg run_command incnmaster "$2"
      dwmc decnmaster ;;

  incgaps) dwm-msg run_command setgaps   5  ;;
  decgaps) dwm-msg run_command setgaps '-5' ;;

  getcurrtag) get_current_tag ;;
  getlayoutname) get_current_layout_name ;;
  getlayoutlist) echo "$layout_list" | awk NF ;;

  togglebarall) currtag=$(dwmc getcurrtag); dwmc viewall;
                dwmc togglebar; dwmc view $currtag ;;

  "") echo dwm control script; exit ;;
  *) eval "dwm-msg run_command $*" ;;
esac
}

getbin ()
{
    [ -z "$1" ] && echo 0 && return
    tag=$1
    [ "$tag" -gt 9 ] || [ "$tag" -lt 1 ] && return
    echo $((1 << tag-1))
}

set_layout ()
{
    get_layout_address_list | sed "${1}q;d" |
        xargs dwm-msg run_command setlayoutsafe
}

get_current_tag ()
{
    dwm-msg get_monitors | jq '.[].tagset.current' |
        xargs sh -c '
            bin="$(echo "obase=2;${1}" | bc)"
            echo "${#bin}"
            ' "${0}"
}

get_layout_address_list ()
{
    dwm-msg get_layouts | jq '.[].address'
}

get_current_layout_address ()
{
    dwm-msg get_monitors | jq -r '.[].layout.address.current'
}

get_current_layout_number ()
{
    get_layout_address_list | awk '$0~'"$(get_current_layout_address)"'{print NR}'
}

get_current_layout_name ()
{
    echo "$layout_list" | awk NF | sed "$(get_current_layout_number)q;d"
}

get_numberof_masters ()
{
    dwm-msg get_monitors | jq '.[].num_master'
}

main "$@"
exit 0
