#!/bin/sh

transp () {
    opaque -0 $TERMINAL >/dev/null 2>&1
}
semitransp () {
    opaque -2 $TERMINAL >/dev/null 2>&1
}
notransp () {
    opaque -1 $TERMINAL >/dev/null 2>&1
}

dwm-msg --ignore-reply subscribe tag_change_event |
jq --unbuffered '.tag_change_event.monitor_number' |
\
while IFS=$'\n' read; do

    case "$(dwmc getlayoutname)" in
        grid | dwindle | tile | deck | spiral | cmaster)
            transp
            ;;
        cfmaster)
            semitransp
            ;;
        monocle | float)
            notransp
            ;;
        *)
            continue
            ;;
    esac
done
