#!/bin/bash
# Koonix 2020-08-23


# Configuration
# Bar update interval
interval=5
# The delimiter character(s) between widgets
delimiter=" ] [ "
enddelimiter=" ]"
bar_prefix=""
# Glyphs/Emojis
glyph_headphone=""
glyph_keyboard=""
glyph_speaker=""
glyph_memory=""
glyph_geoip=""
glyph_temp=""
glyph_time=""


# Trap for updating the statusbar at will
trap 'refresh_bar_sigtrap' SIGTRAP
trap 'refresh_bar_sigalrm' SIGALRM


# Declare the array
declare -a WIDGET


# Stick all the widgets together into a line
build_bar() { \
    statusbar=$(for i in {6..1}
    do
        echo "$delimiter"
        echo "${WIDGET[$i]}"
    done)
}


# Construct the statusbar while updating only some of the widgets
refresh_widgets_set3() { \

    # Netspeed widget
    INDEX=5;
    WIDGET[$INDEX]=$(netspeed enp3s0 | awk '{print $2 "" $6 "KB"}')
}

# Construct the statusbar while updating only some of the widgets
refresh_widgets_set2() { \

    # Keyboard layout widget
    INDEX=2;
    WIDGET[$INDEX]=$(echo "$glyph_keyboard"; xkblayout-state print " %s"; echo)

    # Check if audio is playing through headphones or speakers
    currentsink=$(vol-getcurrentsinkname)
    if [ "$currentsink" = "analog-stereo" ]
    then
        sinkicon="$glyph_headphone"
    else
        sinkicon="$glyph_speaker"
    fi
    # Volume widget
    INDEX=3;
    WIDGET[$INDEX]=$(echo "${sinkicon} "; vol-getcurrentvolumeandmute)

    # Stick all the widgets together into a line
    build_bar
}


# Construct the statusbar
refresh_widgets_set1() { \

    # Time and date widget
    INDEX=1;
    WIDGET[$INDEX]=$(echo -e "$glyph_time"; /usr/bin/date -Im | \
        awk 'BEGIN{FS=OFS="+"} {gsub(/T/, " xx ", $1); print " " $1}')

    # Volume widget
    refresh_widgets_set2

    # Memory usage widget
    INDEX=4;
    WIDGET[$INDEX]=$(/usr/bin/free -h | \
        awk -v glyph="$glyph_memory" '/^Mem:/ {print glyph " " $3}')

    # Netspeed widget
    refresh_widgets_set3

    # GeoIP widget
    INDEX=6;
    WIDGET[$INDEX]=$(geoiplookup "$(curl -s ifconfig.me)" | \
        awk -v glyph="$glyph_geoip" '/^GeoIP/ {gsub(/,/, "", $4); \
        print glyph " " tolower($4)}')

    # CPU temp widget
#    INDEX=6;
#    WIDGET[$INDEX]=$(/usr/bin/sensors | \
#       awk -v glyph="$glyph_temp" '/^Core 0/ {print glyph $3}' | tr '+' ' ')

    # Stick all the widgets together into a line
    build_bar
}


write_bar() { \
    # Remove the first two characters of statusbar (leftover of the delimiter)
    statusbar="${bar_prefix}${statusbar:2}"
    xsetroot -name "$(echo "${statusbar}${enddelimiter}" | tr -d '\n')" &
    wait
}


# Show the constructed statusbar (only refresh set2)
refresh_bar_sigtrap() { \
    refresh_widgets_set2
    write_bar
}


# Show the constructed statusbar
refresh() { \
    refresh_widgets_set1
    write_bar
}


# Refresh the statusbar every 2 seconds
while true ; do
    refresh
    sleep "$interval" &
    wait
done
