#!/bin/sh

if [ "$#" -eq "0" ]; then
  echo "What manual do you want bruv?";
  exit 0
elif ! man -w "$@" > /dev/null; then
  # Check if that manpage exists to prevent visual noise or whatever.
  exit 1
fi

"$HOME/.local/bin/nvim" -c "SuperMan $*" -c "set number"
