#!/bin/sh
# All my keyboard and mouse remapping and settings and stuff is done here.
xmodmaprc="$XDG_CONFIG_HOME/xmodmap/xmodmaprc"
xcaperc="$XDG_CONFIG_HOME/xcape/xcaperc"

# Set keyboard layout and model
setxkbmap -model pc105 -layout us,ir

# Remap one of my mouse's side buttons to middle click
xmodmap "$xmodmaprc"

# Left super acts as escape if pressed and released
# (Capslock is mapped to left super via skr)
killall xcape 2>/dev/null
xcape -e "$(cat "$xcaperc" | awk -F# '{print $1}' | awk NF | tr -d '\n')"

# Advanced: Set key repeat rate
xset r rate 200 60

# Turn off key repeat for media keys
xset -r 121
xset -r 122
xset -r 123

# Disable mouse acceleration
xinput --set-prop 'pointer:G-SPY USB Gaming Mouse'\
    'libinput Accel Profile Enabled' 0, 1
