#!/bin/sh
# Koonix 2020-08-19

# Takes the current volume as an argument and rounds it down to the
# nearest multiple of $ROUND_TO. Also considers $MINVOL and $MAXVOL
# while doing so.

# Some examples (if ROUND_TO=5):
#
#   input value      output value
#    100              95
#    98               95
#    16               15
#    5                0
#    0                0

ROUND_TO=10

VOL=$1
MINVOL=$2
MAXVOL=$3
#if (( VOL > MINVOL && VOL <= MAXVOL ))
if [ "$VOL" -gt "$MINVOL" ] && [ "$VOL" -le "$MAXVOL" ]
then
    NEWVOL=$((((VOL-1)/ROUND_TO)*ROUND_TO))
    echo "$NEWVOL"
else
    echo "$VOL"
fi
